

# *****************************************************************
# *   ___           _           ___                             _ *
# *  / _ \__ _ _ __| |_ _   _  / _ \__ _ _ __ ___   ___  ___   / \*
# * / /_)/ _` | '__| __| | | |/ /_\/ _` | '_ ` _ \ / _ \/ __| /  /*
# */ ___/ (_| | |  | |_| |_| / /_\\ (_| | | | | | |  __/\__ \/\_/ *
# *\/    \__,_|_|   \__|\__, \____/\__,_|_| |_| |_|\___||___/\/   *
# *                     |___/                                     *
# *****************************************************************
#
#         (c) Jayox. All rights reserved
#
# More info at full wiki: https://partygames.gitbook.io/partygames-documentation/
# Support at my discord server: https://discord.gg/tfvqwBbyRG
#
#


# Claim your license to start the plugin
# You can do so on my Discord Server (https://discord.gg/tfvqwBbyRG)
LICENSE_KEY: ''

# Selects a language file located at lang/
# By default available languages are:
# - en
# - es
# If you want to create new languages, go to my discord and create a ticket,
# we will be with you soon
locale: 'en'

# This will be replaced on statistics, and messages where the placeholder {server_name} is used
server-name: 'PartyGames! Test server'

database:
  # Select wich type of database you want to use, if MySQL, you need to specify the host.
  type: SQLite

  # Only replace if using MySQL
  host: 'localhost'
  port: 3306
  dbname: 'PartyGames'
  user: 'root'
  password: ''